//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.08.12 at 10:21:32 PM NZST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.ultraq.net.nz/preferences/xml", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package nz.net.ultraq.preferences.xml;
