//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.05.07 at 04:58:02 PM NZST 
//


package nz.net.ultraq.preferences.xml;

import javax.xml.bind.JAXBElement;
import javax.xml.namespace.QName;

public class Root
    extends JAXBElement<Node>
{

    protected final static QName NAME = new QName("http://www.ultraq.net.nz/preferences/xml", "preferences");

    public Root(Node value) {
        super(NAME, ((Class) Node.class), null, value);
    }

    public Root() {
        super(NAME, ((Class) Node.class), null, null);
    }

}
