//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.05.11 at 03:01:48 PM NZST 
//


package nz.net.ultraq.preferences.xml;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementWrapper;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Node complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Node">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="entries" type="{http://www.ultraq.net.nz/preferences/xml}Entries" minOccurs="0"/>
 *         &lt;element name="nodes" type="{http://www.ultraq.net.nz/preferences/xml}Nodes" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Node", propOrder = {
    "entries",
    "nodes"
})
@XmlSeeAlso({
    XMLRoot.class
})
public class XMLNode {

    @XmlAttribute(name = "name", required = true)
    protected String name;
    @XmlElementWrapper(name = "entries")
    @XmlElement(name = "entry")
    protected List<XMLEntry> entries;
    @XmlElementWrapper(name = "nodes")
    @XmlElement(name = "node")
    protected List<XMLNode> nodes;

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    public List<XMLEntry> getEntries() {
        if (entries == null) {
            entries = new ArrayList<XMLEntry>();
        }
        return entries;
    }

    public List<XMLNode> getNodes() {
        if (nodes == null) {
            nodes = new ArrayList<XMLNode>();
        }
        return nodes;
    }

}
