//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.12.07 at 10:02:15 PM NZDT 
//


package nz.net.ultraq.preferences.xml;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the nz.net.ultraq.preferences.xml package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: nz.net.ultraq.preferences.xml
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link XmlRoot }
     * 
     */
    public XmlRoot createXmlRoot() {
        return new XmlRoot();
    }

    /**
     * Create an instance of {@link XmlEntry }
     * 
     */
    public XmlEntry createXmlEntry() {
        return new XmlEntry();
    }

    /**
     * Create an instance of {@link XmlNode }
     * 
     */
    public XmlNode createXmlNode() {
        return new XmlNode();
    }

}
