//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.12.07 at 10:02:15 PM NZDT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.ultraq.net.nz/preferences/xml", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package nz.net.ultraq.preferences.xml;
