//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.12.24 at 07:47:46 PM NZDT 
//


package nz.net.ultraq.preferences.xml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for preferences element declaration.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;element name="preferences">
 *   &lt;complexType>
 *     &lt;complexContent>
 *       &lt;extension base="{http://www.ultraq.net.nz/preferences/xml}Node">
 *       &lt;/extension>
 *     &lt;/complexContent>
 *   &lt;/complexType>
 * &lt;/element>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "")
@XmlRootElement(name = "preferences")
public class XMLRoot
    extends XMLNode
{

    
	/**
	 * Default constructor. 
	 */
	public XMLRoot() {
	}

	/**
	 * Constructor, set the name of this node.
	 * 
	 * @param name
	 */
	public XMLRoot(String name) {

		super(name);
	}
				
}
